export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USER_FAIL';
export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const LOG_OUT = 'LOG_OUT';


export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';


export const JOIN_GAME_REQUEST = 'JOIN_GAME_REQUEST';
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS';
export const JOIN_GAME_FAIL = 'JOIN_GAME_FAIL';
export const LEAVE_GAME = 'LEAVE_GAME';
export const SET_SELF_PROGRESS = 'SET_SELF_PROGRESS';