export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USER_FAIL';
export const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
export const LOG_OUT = 'LOG_OUT';


export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';